fs: 48000
room_dim:
- 10.189
- 10.189
- 3.5
room_floor_m2: 103.81
source_pos:
- 2.023
- 5.211
- 1.917
azimuth_deg: 177.83
elevation_deg: 3.1
source_distance_m: 3.078
fullband_T30_ms: 515.2
mic: tetra r=0.05
target_asl_dB: 98.72
foa_format: SN3D ACN (WXYZ)
