fs: 48000
room_dim:
- 9.574
- 9.574
- 2.86
room_floor_m2: 91.66
source_pos:
- 6.968
- 2.954
- 2.46
azimuth_deg: -40.05
elevation_deg: 19.87
source_distance_m: 3.03
fullband_T30_ms: 252.0
mic: tetra r=0.05
target_asl_dB: 86.14
foa_format: SN3D ACN (WXYZ)
