fs: 48000
room_dim:
- 10.455
- 10.455
- 2.557
room_floor_m2: 109.31
source_pos:
- 5.237
- 7.528
- 0.459
azimuth_deg: 89.76
elevation_deg: -19.62
source_distance_m: 2.442
fullband_T30_ms: 633.5
mic: tetra r=0.05
target_asl_dB: 88.97
foa_format: SN3D ACN (WXYZ)
