fs: 48000
room_dim:
- 15.446
- 15.446
- 3.128
room_floor_m2: 238.58
source_pos:
- 7.169
- 8.977
- 0.465
azimuth_deg: 113.85
elevation_deg: -38.72
source_distance_m: 1.757
fullband_T30_ms: 198.4
mic: tetra r=0.05
target_asl_dB: 91.43
foa_format: SN3D ACN (WXYZ)
