fs: 48000
room_dim:
- 14.981
- 14.981
- 3.342
room_floor_m2: 224.44
source_pos:
- 5.344
- 7.113
- 2.249
azimuth_deg: -170.01
elevation_deg: 14.86
source_distance_m: 2.255
fullband_T30_ms: 1627.3
mic: tetra r=0.05
target_asl_dB: 97.43
foa_format: SN3D ACN (WXYZ)
