fs: 48000
room_dim:
- 15.471
- 15.471
- 2.87
room_floor_m2: 239.36
source_pos:
- 6.781
- 8.243
- 2.287
azimuth_deg: 152.01
elevation_deg: 38.26
source_distance_m: 1.376
fullband_T30_ms: 358.0
mic: tetra r=0.05
target_asl_dB: 87.06
foa_format: SN3D ACN (WXYZ)
