fs: 48000
room_dim:
- 10.95
- 10.95
- 3.018
room_floor_m2: 119.9
source_pos:
- 5.935
- 5.071
- 1.128
azimuth_deg: -41.26
elevation_deg: -31.95
source_distance_m: 0.721
fullband_T30_ms: 366.4
mic: tetra r=0.05
target_asl_dB: 90.02
foa_format: SN3D ACN (WXYZ)
