fs: 48000
room_dim:
- 16.551
- 16.551
- 3.735
room_floor_m2: 273.94
source_pos:
- 8.592
- 6.364
- 1.367
azimuth_deg: -80.61
elevation_deg: -14.47
source_distance_m: 2.001
fullband_T30_ms: 454.9
mic: tetra r=0.05
target_asl_dB: 97.08
foa_format: SN3D ACN (WXYZ)
